<?php

namespace ArtMeBlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoemRepository extends \Doctrine\ORM\EntityRepository
{
}
